import localFont from "next/font/local";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.min.css"
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/components/Header/Header";
import BootstrapClient from "@/libs/bootstrapClient";
import "@/utils/color-modes";
import ColorModeScript from "@/libs/ColorModeScript";
import Footer, { socialLinks } from "@/components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">
          <Header />
          {children}
          <Footer companyName="Suveesoft"
            year={2024}
            links={{
              companyUrl: 'https://suveesoft.in/',
              socialLinks: socialLinks
            }} />
        </div>
        <BootstrapClient />
        <ColorModeScript />
      </body>
    </html>
  );
}
